
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-study-kni-arch-org-v1alpha1-simple
  failurePolicy: Fail
  name: msimple.kb.io
  rules:
  - apiGroups:
    - study.kni-arch.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - simples
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-study-kni-arch-org-v1alpha2-simple
  failurePolicy: Fail
  name: msimple.kni-arch.org
  rules:
  - apiGroups:
    - study.kni-arch.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - simples

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-study-kni-arch-org-v1alpha1-simple
  failurePolicy: Fail
  name: vsimple.kb.io
  rules:
  - apiGroups:
    - study.kni-arch.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - simples
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-study-kni-arch-org-v1alpha2-simple
  failurePolicy: Fail
  name: vsimple.kni-arch.org
  rules:
  - apiGroups:
    - study.kni-arch.org
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - simples
